  export const pages = [
    {
        title: 'A Creeking Sound in the Floor Boards',
        text: `The officers were so kind, so utterly unsuspecting. They sat across from me, their uniforms crisp, their faces open and trusting. How easily they swallowed my words, my calm demeanor, my practiced smiles. And all the while, beneath their very feet, it lay—the thing I had buried.\nThey had come on account of the noise, they said. A neighbor had reported a scream in the night. A scream? I laughed—a light, airy sound that did not betray the hammering in my chest. "A nightmare, perhaps," I suggested. "The walls in these old houses carry sound so strangely."\nThe taller officer nodded, his eyes scanning the room. "You live here alone?"\n"Quite alone," I said, folding my hands neatly in my lap. My pulse was a frantic drum, but my voice was steady. Steady as the dead.\nAnd then—there it was. A creak.\nA soft, groaning whine from the floorboards beneath the rug. My breath hitched, but I forced another smile. The officers did not seem to notice. They chatted idly, sipping the tea I had offered, oblivious to the horror just inches below.\nBut I heard it. Oh, I heard it.\nEvery shift of their weight, every casual tap of a boot against`,
        chapter: 'Seven',
        page: 391
    },
    {
        text: `the wood—each sound was a spike driven into my skull. The floor was speaking to me, whispering its betrayal. The body was not as deep as it should have been. I had been in such haste, such trembling, feverish haste.\n"You've lived here long?" the shorter officer asked.\n"Years," I replied, my throat dry. Another creak—louder this time. My fingers twitched. Did they hear it? Did they sense the wrongness in the air?\nThe taller officer shifted in his chair, his heel pressing down—\nCreeeak. A sound like a moan. Like a voice.\nI laughed again, too sharp, too quick. "Old houses," I said, "always settling."\nBut the officers were not looking at me anymore. The shorter one frowned, tilting his head slightly. "You hear that?"\nMy blood turned to ice. "Hear what?"\nHe leaned forward, listening. The floor groaned beneath him.\nCreeeak. The sound was unmistakable now—a slow, drawn-out protest from the wood. As if something beneath was stirring.\nThe taller officer stood, his chair scraping back. "That's… odd."\nI stood as well, my hands trembling. "Just the foundation," I said, too quickly. "The damp air makes the wood—" Creeeak.\nLouder. Longer. A sound that was not natural, not explainable.\nThe shorter officer knelt, pressing a hand to the floor. "Feels…\n`,
        page: 392
    },
    {
        text: `My heart was a wild thing, thrashing against my ribs. They would lift the rug. They would see the fresh-cut planks, the hastily replaced nails. They would know.\nThe taller officer reached for the edge of the rug—\nI screamed.\nA raw, guttural sound, ripped from my throat. Both men startled, staring at me in shock.\n"Leave it!" I shrieked. "For God's sake, leave it be!"\nSilence. Terrible, suffocating silence.\nAnd then— Creeeak. A final, shuddering groan from the floor.\nThe officers exchanged a glance. The shorter one reached again for the rug— I could bear it no longer. "Yes!" I cried, clawing at my hair. "Yes, I did it! I confess! It's here—right here beneath you! I buried him there! I couldn't stand the sound of his breathing, the sound of his heart—and now the floor won't stop, it won't stop, it won't stop—!"\nThe officers moved swiftly then, prying up the boards. And there he was, pale and staring, his mouth frozen in a silent scream.\nBut worst of all—worse than the stench, worse than the sight—was the sound.\nThe creaking did not stop.\nEven as they dragged me away, even as the house emptied of all but the dead—the floor still whispered.\nAnd I knew, as I had always known, that the dead do not rest quietly.`,
        page: 393
    }
];